### ISSUE TITLE
Additional Parameters 

### ISSUE THREAD

**Issue by mikeypatt** [BYUFLOWLab/pyfmincon#3]
Hi mate, I just found this. I was wondering how I would include extra parameters that my objective function requires that aren't independent variables? They are big arrays. I can't just add them and include make the upper and lower bounds equal the value as they are different for each element in the array. Is there a way to do a similar function handle fix like in actual matlab?

**Comment by andrewning** [comment]
A function closure or anonymous function would be the standard way to do this.
