### ISSUE TITLE
Exception "Unable to resolve the name py.example.barnes." while running the exampl.py file

### ISSUE THREAD

**Issue by TAM360** [BYUFLOWLab/pyfmincon#4]
Hi, 

I am trying to play around with **example.py** file. However, whenever I run the file, I get the following exception:
	Unable to resolve the name py.example.barnes.

	Error in optimize/fupdate (line 41)
		eval(['output = py.', funcname, '(x);'])  % output is a cell array with {J, cin}

	Error in optimize/obj (line 59)
		[J, cin, gJ, gcin] = fupdate(x);

	Error in fmincon (line 571)
	      [initVals.f,initVals.g] = feval(funfcn{3},X,varargin{:});

	Error in optimize (line 25)
	    [xopt, fopt, exitflag, output] = fmincon(@obj, x0, A, b, Aeq, beq, lb, ub, @con, options);

	Caused by:
	    Failure in initial objective function evaluation. FMINCON cannot continue.

	Traceback (most recent call last):
	  File "exp.py", line 165, in <module>
	    function, x0, lb, ub, options, providegradients=providegradients
	  File "/home/tam/Documents/codes/python/hassan/opt.py", line 47, in fmincon
 	Aeq, beq, lb, ub, options, providegradients, nargout=4)
	 File "/usr/local/lib/python3.6/dist-packages/matlab/engine/		matlabengine.py", line 71, in __call__
	    _stderr, feval=True).result()
	  File "/usr/local/lib/python3.6/dist-packages/matlab/engine/futureresult.py", line 67, in result
	    return self.__future.result(timeout)
	  File "/usr/local/lib/python3.6/dist-packages/matlab/engine/fevalfuture.py", line 82, in result
	    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
	matlab.engine.MatlabExecutionError: 
	  File /home/tam/Documents/codes/python/hassan/optimize.m, line 41, in optimize/fupdate

	  File /home/tam/Documents/codes/python/hassan/optimize.m, line 59, in optimize/obj

	  File /home/tam/matlab/toolbox/shared/optimlib/fmincon.m, line 571, in fmincon

	  File /home/tam/Documents/codes/python/hassan/optimize.m, line 25, in optimize
	Unable to resolve the name py.example.barnes.

Is there any step involved other than simply running example.py file? If not then what's the exact problem in this case?

**Comment by andrewning** [comment]
We haven't used this in years as all our development has shifted to Julia.  At the time we were using Python 2.7 so there may be some small python3 updates needed.  Having said that it looks like the problem is with matlab finding the python module.  I'd try to see if you can call a simple python file from matlab.  May require some configuring.
